import Head from 'next/head'
import Image from 'next/image'
import Pokemon from '../components/pokemon'
import styles from '../styles/Home.module.css'

export default function Home({ pokemons }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {pokemons.results.map((pokemon, i) => {
          return (
            <Pokemon pokemon={pokemon} key={i} />
          )
        })}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {

  const res = await fetch(`https://pokeapi.co/api/v2/pokemon`);
  const pokemons = await res.json();

  return {
    props: {
      pokemons
    }, // will be passed to the page component as props
  }
}